djangoynode/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from principal.views import IndexView,InicioView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'djangoynode.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', IndexView.as_view()),
    url(r'^inicio/$', InicioView.as_view()),
    url(r'^crear-comentario$', 'principal.views.create_comment'),
    url(r'^admin/', include(admin.site.urls)),
)

principal/models.py
from django.db import models

# Create your models here.


class Comment(models.Model):
	user = models.CharField(max_length=50)
	comment = models.TextField()

principal/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):

	class Meta:
		model = Comment

principal/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse

from .forms import CommentForm
from .models import Comment
# Create your views here.


class IndexView(TemplateView):

	template_name = 'index.html'

	def post(self, request, *args, **kwargs):
		request.session['name'] = request.POST['name']
		return redirect('/inicio/')

class InicioView(TemplateView):
	def get(self, request, *args, **kwargs):
		if request.session.get('name'):
			comments = Comment.objects.all()
			dic = {
				'name' : request.session['name'],
				'form' : CommentForm(),
				'comments' : comments
			}				
			return render(request, 'inicio.html', dic)
		else:
			return redirect('/')

	def post(self, request, *args, **kwargs):
		Comment.objects.create(
				user = request.session['name'],
				comment = request.POST['comment']	
			)
		return redirect('/inicio/')


@csrf_exempt
def create_comment(request):	
	Comment.objects.create(
			user = request.POST['user'],
			comment = request.POST['comment']
		)
	response = JsonResponse({'user' : request.POST['user'],
							'comment' : request.POST['comment']})
	return HttpResponse(response.content)

principal/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>django y node</title>
</head>
<body>
	<h1>Ingresa a la aplicacion</h1>
	<form method="POST">
		{% csrf_token %}
		<input type="text" name="name" placeholder"Ingresa un nombre">
		<input type="submit" value="Ingresa">
	</form>
</body>
</html>

principal/templates/inicio.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Bienvenido</title>
</head>
<body>
	<h1>hola {{ name }}</h1>

	<hr>
	<div id="comentarios">
	{% for comment in comments %}
		
	<p>{{ comment.user }} - {{ comment.comment }}</p>

	{% endfor %}
	</div>


	<form>
		{% csrf_token %}
		{{ form.comment }}
		<button id="boton">Comentar</button>		
	</form>
	<script type='text/javascript' src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script> 
	<script src="http://localhost:3000/socket.io/socket.io.js"></script>
	<script>
		var socket = io.connect("http://localhost:3000");

		$('#boton').on('click', Comentar);

		function Comentar(e){
			e.preventDefault();
			var datos = {
				user : "{{ name }}",
				comment : $('#id_comment').val()
			}
			socket.emit('nuevo comentario', datos);
		}
		socket.on('devolviendo comentario', function (data){
			var data = JSON.parse(data);
			$("#comentarios").prepend("<p>" + data.user + " - " + data.comment + "</p>");
		});
	</script>
</body>
</html>